# 1. Scrape the details of most viewed videos on YouTube from Wikipedia: Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ You need to find following details:
A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [74]:
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
import pandas as pd
import time
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By

In [103]:
rank=[]
name_of_video=[]
artist=[]
upload_date=[]
views=[]

In [107]:
def youtube(url):
    driver=webdriver.Chrome('chromedriver.exe')
    driver.get(url)
    Rank=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[1]")
    for r in Rank[0:30]:
        rank.append(r.text)
        time.sleep(2)
    
    name=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]")
    for n in name[0:30]:
        name_of_video.append(n.text)
        time.sleep(2)
        
    art=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]")
    for a in art[0:30]:
        artist.append(a.text)
        time.sleep(2)
    
    Views=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]")
    for vw in Views[0:30]:
        views.append(vw.text)
        time.sleep(2)
        
    upload=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]")
    for up in upload[0:30]:
        upload_date.append(up.text)
        time.sleep(2)

In [108]:
youtube('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [116]:
top_video=pd.DataFrame({"Rank":rank[0:30],
                       "Video Name":name_of_video[0:30],
                       "Artist":artist[0:30],
                       "Views":views[0:30],
                       "Upload Date":upload_date[0:30]})
top_video
top_video.set_index('Rank')

,Video Name,Artist,Views,Upload Date
Rank,,,,
1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,8.44,"June 17, 2016"
2.,"""Despacito""[24]",Luis Fonsi,7.32,"January 12, 2017"
3.,"""Shape of You""[25]",Ed Sheeran,5.29,"January 30, 2017"
4.,"""Johny Johny Yes Papa""[26]",LooLoo Kids,5.24,"October 8, 2016"
5.,"""See You Again""[27]",Wiz Khalifa,5.08,"April 6, 2015"
6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.43,"January 31, 2012"
7.,"""Uptown Funk""[31]",Mark Ronson,4.16,"November 19, 2014"
8.,"""Gangnam Style""[32]",Psy,4.05,"July 15, 2012"
9.,"""Learning Colors – Colorful Eggs on a Farm""[34]",Miroshka TV,3.97,"February 27, 2018"
10.,"""Bath Song""[35]",Cocomelon – Nursery Rhymes,3.95,"May 2, 2018"
11.,"""Phonics Song with Two Words""[36]",ChuChu TV,3.78,"March 6, 2014"
12.,"""Sugar""[37]",Maroon 5,3.45,"January 14, 2015"
13.,"""Sorry""[38]",Justin Bieber,3.43,"October 22, 2015"
14.,"""Roar""[39]",Katy Perry,3.34,"September 5, 2013"
15.,"""Dame Tu Cosita""[40]",El Chombo,3.28,"April 5, 2018"
16.,"""Counting Stars""[41]",OneRepublic,3.27,"May 31, 2013"
17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.24,"October 7, 2014"
18.,"""Dark Horse""[43]",Katy Perry,3.05,"February 20, 2014"
19.,"""Faded""[44]",Alan Walker,3.05,"December 3, 2015"
20.,"""Shake It Off""[45]",Taylor Swift,3.05,"August 18, 2014"
21.,"""Lean On""[46]",Major Lazer Official,3.02,"March 22, 2015"
22.,"""Bailando""[47]",Enrique Iglesias,3.01,"April 11, 2014"
23.,"""Girls Like You""[48]",Maroon 5,3.01,"May 31, 2018"
24.,"""Let Her Go""[49]",Passenger,2.97,"July 25, 2012"
25.,"""Mi Gente""[50]",J Balvin,2.90,"June 29, 2017"
26.,"""Wheels on the Bus""[51]",Cocomelon – Nursery Rhymes,2.89,"May 24, 2018"
27.,"""Hello""[52]",Adele,2.83,"October 22, 2015"
28.,"""Perfect""[53]",Ed Sheeran,2.82,"November 9, 2017"
29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,2.80,"June 4, 2010"
30.,"""Axel F""[55]",Crazy Frog,2.77,"June 16, 2009"

# 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details:
A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [100]:
import pandas as pd
import selenium
import time
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

In [101]:
Series=[]
Place=[]
Date=[]
Month=[]
Time=[]
Match_Title=[]

In [102]:
def Fixture(url):
    driver=webdriver.Chrome('chromedriver.exe')
    driver.get(url)
    fix=driver.find_element_by_xpath("//div[@class='navigation__menu-container']/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a")
    fixture=fix.get_attribute('href')
    driver.get(fixture)
    
    date=driver.find_elements_by_xpath("//div[@class='fixture__full-date']/span")
    for d in date:
        Date.append(d.text)
    
    month=driver.find_elements_by_xpath("//div[@class='fixture__date-details']/span[1]")
    for m in month:
        Month.append(m.text)
        
    time=driver.find_elements_by_xpath("//div[@class='fixture__date-details']/span[2]")
    for t in time:
        Time.append(t.text)
    
    
    place=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/span")
    for p in place:
        Place.append(p.text)
    
    
    series=driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[2]")
    for s in series:
        Series.append(s.text)
    
    
    match_title=driver.find_elements_by_xpath("//div[@class='fixture__description u-unskewed-text']/p/strong")
    for mt in match_title:
        Match_Title.append(mt.text)
    
    

Fixture('https://www.bcci.tv/')

In [103]:
international_fixture=pd.DataFrame({"Match Title":Match_Title,
                                   "Series":Series,
                                   "Place":Place,
                                   "Date":Date,
                                   "Month":Month,
                                   "Time":Time})
international_fixture

,Match Title,Series,Place,Date,Month,Time
0,Final,ICC WORLD TEST CHAMPIONSHIP FINAL,"The Ageas Bowl, Southampton",18,JUNE,15:30 IST
1,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",04,AUGUST,15:30 IST
2,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",12,AUGUST,15:30 IST
3,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",25,AUGUST,15:30 IST
4,4th Test,ENGLAND V INDIA 2021,"The Oval, London",02,SEPTEMBER,15:30 IST
5,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",10,SEPTEMBER,15:30 IST

# 3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/. You need to find following details:
A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [1]:
import pandas as pd
import selenium
import time
from selenium.common.exceptions import NoSuchElementException
from selenium import webdriver

In [2]:
table_exception=[]
table_description=[]

In [3]:
def selenium(url):
    driver=webdriver.Chrome('chromedriver.exe')
    driver.get(url)
    
    selenium=driver.find_element_by_xpath("//li[@class='fa fa-chevron-circle-right'][3]/a")
    selenium_ex=selenium.get_attribute('href')
    driver.get(selenium_ex)
    
    selenium_tutorial=driver.find_element_by_xpath("//table[@class='table'][5]/tbody/tr[34]/td[1]/a")
    selenium_ex1=selenium_tutorial.get_attribute('href')
    driver.get(selenium_ex1)
    
    table=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for t in table[0:42]:
        table_exception.append(t.text)
        
    table1=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for t1 in table1[0:42]:
        table_description.append(t1.text)
    
selenium('https://www.guru99.com/')

In [4]:
Selenium_exception=pd.DataFrame({'Exception Name':table_exception[0:42],
                                'Description':table_description[0:42]})
Selenium_exception

,Exception Name,Description
0,Exception name,Description
1,ElementNotVisibleException,This type of Selenium exception occurs when an...
2,ElementNotSelectableException,This Selenium exception occurs when an element...
3,NoSuchElementException,This Exception occurs if an element could not ...
4,NoSuchFrameException,This Exception occurs if the frame target to b...
5,NoAlertPresentException,This Exception occurs when you switch to no pr...
6,NoSuchWindowException,This Exception occurs if the window target to ...
7,StaleElementReferenceException,This Selenium exception occurs happens when th...
8,SessionNotFoundException,The WebDriver is acting after you quit the bro...
9,TimeoutException,Thrown when there is not enough time for a com...
10,WebDriverException,This Exception takes place when the WebDriver ...
11,ConnectionClosedException,This type of Exception takes place when there ...
12,ElementClickInterceptedException,The command may not be completed as the elemen...
13,ElementNotInteractableException,This Selenium exception is thrown when any ele...
14,ErrorInResponseException,This happens while interacting with the Firefo...
15,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
16,ImeActivationFailedException,This expectation will occur when IME engine ac...
17,ImeNotAvailableException,It takes place when IME support is unavailable.
18,InsecureCertificateException,Navigation made the user agent to hit a certif...
19,InvalidArgumentException,It occurs when an argument does not belong to ...
20,InvalidCookieDomainException,This happens when you try to add a cookie unde...
21,InvalidCoordinatesException,This type of Exception matches an interacting ...
22,InvalidElementStateExceptio,It occurs when command can't be finished when ...
23,InvalidSessionIdException,This Exception took place when the given sessi...
24,InvalidSwitchToTargetException,This occurs when the frame or window target to...
25,JavascriptException,This issue occurs while executing JavaScript g...
26,JsonException,It occurs when you afford to get the session w...
27,NoSuchAttributeException,This kind of Exception occurs when the attribu...
28,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
29,NoSuchContextException,ContextAware does mobile device testing.
30,NoSuchCookieException,This Exception occurs when no cookie matching ...
31,NotFoundException,This Exception is a subclass of WebDriverExcep...
32,RemoteDriverServerException,This Selenium exception is thrown when the ser...
33,ScreenshotException,It is not possible to capture a screen.
34,SessionNotCreatedException,It happens when a new session could not be suc...
35,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
36,UnexpectedTagNameException,Happens if a support class did not get a web e...
37,UnhandledAlertException,This expectation occurs when there is an alert...
38,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
39,UnknownMethodException,This Exception happens when the requested comm...
40,UnreachableBrowserException,This Exception occurs only when the browser is...
41,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/. You have to find following details:
A) Rank

B) State

C) GSDP(18-19)

D) GSDP(17-18)

E) Share(2017)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code

In [153]:
import pandas as pd
import selenium
import time
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [154]:
driver=webdriver.Chrome('chromedriver.exe')
driver.get('http://statisticstimes.com/')

In [155]:
eco=driver.find_element_by_xpath("//div[@class='dropdown-content']/a[3]")
eco1=eco.get_attribute('href')
driver.get(eco1)

In [156]:
state=driver.find_element_by_xpath("//a[@href='india/indian-states-gdp.php']")
state.click()

In [157]:
Rank=[]
State=[]
GSDP=[]
Share=[]
GDP=[]
Current_GSDP=[]

In [158]:
rank=driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[1]")
for r in rank[0:33]:
    Rank.append(r.text)

In [159]:
state=driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[2]")
for s in state[0:33]:
    State.append(s.text)

In [160]:
gsdp=driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[4]")
for g in gsdp[0:33]:
    GSDP.append(g.text)

In [161]:
gsdp_share=driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[5]")
for gs in gsdp_share[0:33]:
    Share.append(gs.text)

In [162]:
gdp=driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[6]")
for b in gdp[0:33]:
    GDP.append(b.text)

In [163]:
current_gsdp=driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[3]")
for cg in current_gsdp[0:33]:
    Current_GSDP.append(cg.text)

In [164]:
State_wise_GDP=pd.DataFrame({'Rank':Rank,
                            'State':State,
                            '19-20':Current_GSDP,
                            '18-19':GSDP,
                            'Share 18-19':Share,
                            'GDP 2019':GDP})
State_wise_GDP

   Rank                      State      19-20      18-19 Share 18-19 GDP 2019
0     1                Maharashtra          -  2,632,792      13.88%  398.145
1     2                 Tamil Nadu  1,845,853  1,630,208       8.59%  246.529
2     3              Uttar Pradesh  1,687,818  1,584,764       8.35%  239.656
3     4                    Gujarat          -  1,502,899       7.92%  227.276
4     5                  Karnataka  1,631,977  1,493,127       7.87%  225.798
5     6                West Bengal  1,253,832  1,089,898       5.75%  164.820
6     7                  Rajasthan  1,020,989    942,586       4.97%  142.543
7     8             Andhra Pradesh    972,782    862,957       4.55%  130.501
8     9                  Telangana    969,604    861,031       4.54%  130.210
9    10             Madhya Pradesh    906,672    809,592       4.27%  122.431
10   11                     Kerala          -    781,653       4.12%  118.206
11   12                      Delhi    856,112    774,870       4.08%  117.180
12   13                    Haryana    831,610    734,163       3.87%  111.024
13   14                      Bihar    611,804    530,363       2.80%   80.204
14   15                     Punjab    574,760    526,376       2.77%   79.601
15   16                     Odisha    521,275    487,805       2.57%   73.768
16   17                      Assam          -    315,881       1.67%   47.769
17   18               Chhattisgarh    329,180    304,063       1.60%   45.982
18   19                  Jharkhand    328,598    297,204       1.57%   44.945
19   20                Uttarakhand          -    245,895       1.30%   37.186
20   21            Jammu & Kashmir          -    155,956       0.82%   23.584
21   22           Himachal Pradesh    165,472    153,845       0.81%   23.265
22   23                        Goa     80,449     73,170       0.39%   11.065
23   24                    Tripura     55,984     49,845       0.26%    7.538
24   25                 Chandigarh          -     42,114       0.22%    6.369
25   26                 Puducherry     38,253     34,433       0.18%    5.207
26   27                  Meghalaya     36,572     33,481       0.18%    5.063
27   28                     Sikkim     32,496     28,723       0.15%    4.344
28   29                    Manipur     31,790     27,870       0.15%    4.215
29   30                   Nagaland          -     27,283       0.14%    4.126
30   31          Arunachal Pradesh          -     24,603       0.13%    3.721
31   32                    Mizoram     26,503     22,287       0.12%    3.370
32   33  Andaman & Nicobar Islands          -          -           -        -

# 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/. You have to find the following details:
A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [13]:
import pandas as pd
import selenium
import time
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [14]:
Repository_Name=[]
Repository_Description=[]
Contributer_Count=[]
Language_used=[]

In [15]:
def github(url):
    driver=webdriver.Chrome('chromedriver.exe')
    driver.get(url)
    
    trending=driver.find_element_by_xpath("//nav[@class='mt-0 px-3 px-lg-0 mb-5 mb-lg-0']/ul/li[4]/details/summary")
    trending.click()
    
    trending1=driver.find_element_by_xpath("//div[@class='dropdown-menu flex-auto rounded px-0 pt-2 pb-0 mt-0 pb-4 p-lg-4 position-relative position-lg-absolute left-0 left-lg-n4']/ul[2]/li[3]/a")
    trending2=trending1.get_attribute('href')
    driver.get(trending2)
    
    time.sleep(2)
    try:
        rep_nam=driver.find_elements_by_xpath("//article[@class='Box-row']/h1/a")
        for rn in rep_nam:
            Repository_Name.append(rn.text)
    except NoSuchElementException as e:
        Repository_Name.append('-')
    
    time.sleep(2)
    try:
        rep_des=driver.find_elements_by_xpath("//p[@class='col-9 color-text-secondary my-1 pr-4']")
        for rd in rep_des:
            Repository_Description.append(rd.text)
    except NoSuchElementException as e:
        Repository_Description.append('-')
    
    time.sleep(2)
    try:
        contri_count=driver.find_elements_by_xpath("//div[@class='f6 color-text-secondary mt-2']/a[2]")
        for cc in contri_count:
            Contributer_Count.append(cc.text)
    except NoSuchElementException as e:
        Contributer_Count.append('-')
        
    time.sleep(2)
    try:
        lang_used=driver.find_elements_by_xpath("//div[@class='f6 color-text-secondary mt-2']/span[1]/span[2]")
        for lu in lang_used:
            Language_used.append(lu.text)
    except NoSuchElementException as e:
        Language_used.append('-')
    
    
github('https://github.com/')

In [37]:
GitHub=pd.DataFrame({'Repository title':Repository_Name[0:20],'Repository description':Repository_Description[0:20],'Contributors count':Contributer_Count[0:20],'Language used':Language_used[0:20]})
GitHub

,Repository title,Repository description,Contributors count,Language used
0,pallupz / covid-vaccine-booking,This very basic script can be used to automate...,127,Python
1,slidevjs / slidev,Presentation Slides for Developers (Public Bet...,74,TypeScript
2,Uniswap / uniswap-v3-core,🦄 🦄 🦄 Core smart contracts of Uniswap v3,152,TypeScript
3,pixie-labs / pixie,Instant Kubernetes-Native Application Observab...,54,C++
4,flutter / flutter,Flutter makes it easy and fast to build beauti...,"17,064",Dart
5,axios / axios,Promise based HTTP client for the browser and ...,"8,149",JavaScript
6,andymatuschak / orbit,very currency,18,TypeScript
7,dogecoin / dogecoin,Responsive Admin Panel or Dashboard using Flutter,"1,562",C++
8,abuanwar072 / Flutter-Responsive-Admin-Panel-o...,"Master the command line, in one page",180,Dart
9,jlevy / the-art-of-command-line,A collective list of free APIs,"9,806",Python
10,public-apis / public-apis,A complete computer science study plan to beco...,"14,985",Go
11,jwasham / coding-interview-university,kcp is a prototype of a Kubernetes API server ...,"46,265",JavaScript
12,kcp-dev / kcp,👩‍💻👨‍💻 Awesome cheatsheets for popular program...,29,Swift
13,LeCoupa / awesome-cheatsheets,"A collection of inspiring lists, manuals, chea...","3,169",Python
14,trimstray / the-book-of-secret-knowledge,Build your own 'AirTags' 🏷 today! Framework fo...,"4,160",Python
15,seemoo-lab / openhaystack,"A curated list of awesome Python frameworks, l...",71,C
16,vinta / awesome-python,a CLI that provides a generic automation layer...,"18,934",TypeScript
17,Azure / counterfit,经典编程书籍大全，涵盖：计算机系统与网络、系统架构、算法与数据结构、前端开发、后端开发、移动...,24,Rust
18,imarvinle / awesome-cs-books,Audio Editor,682,Java
19,audacity / audacity,🦄 🦄 🦄 Peripheral smart contracts for interacti...,"1,040",TypeScript

# 6. Scrape the details of top 100 songs on billiboard.com. Url = https://www.billboard.com/. You have to find the following details:
A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [50]:
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [51]:
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.billboard.com/')

In [52]:
bill_board=driver.find_element_by_xpath("//div[@class='header__main-menu__wrapper flex--grow']/ul/li[1]/a")
url=bill_board.get_attribute('href')
driver.get(url)

In [53]:
chart_view=driver.find_element_by_xpath("//div[@class='charts-landing__info--view-chart-holder']")
chart_view.click()

In [54]:
Rank=[]
Song_Name=[]
Artist_Name=[]
Last_week_rank=[]
Peak_rank=[]

In [55]:
rank=driver.find_elements_by_xpath("//div[@Class='chart-list container ']/ol/li/button/span[1]/span[1]")
for r in rank[:100]:
    Rank.append(r.text)

In [56]:
song_name=driver.find_elements_by_xpath("//div[@Class='chart-list container ']/ol/li/button/span[2]/span[1]")
for sn in song_name[:100]:
    Song_Name.append(sn.text)

In [57]:
artist_name=driver.find_elements_by_xpath("//div[@Class='chart-list container ']/ol/li/button/span[2]/span[2]")
for an in artist_name[:100]:
    Artist_Name.append(an.text)

In [58]:
last_week_rank=driver.find_elements_by_xpath("//div[@Class='chart-list container ']/ol/li/button/div/div[2]")
for lwr in last_week_rank[:100]:
    Last_week_rank.append(lwr.text)

In [59]:
peak_rank=driver.find_elements_by_xpath("//div[@Class='chart-list container ']/ol/li/button/div/div[3]")
for pw in peak_rank[:100]:
    Peak_rank.append(pw.text)

In [61]:
Billboard=pd.DataFrame({'Rank':Rank,'Song Name':Song_Name,'Artist':Artist_Name,'Last Week Rank':Last_week_rank,'Peak Rank':Peak_rank})
Billboard

,Rank,Song Name,Artist,Last Week Rank,Peak Rank
0,1,Save Your Tears,The Weeknd & Ariana Grande,6,1
1,2,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),2,1
2,3,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,3,1
3,4,Rapstar,Polo G,1,3
4,5,Levitating,Dua Lipa Featuring DaBaby,5,5
...,...,...,...,...,...
95,96,4 Da Gang,42 Dugg & Roddy Ricch,100,67
96,97,Blame It On You,Jason Aldean,-,97
97,98,Wasted On You,Morgan Wallen,9,16
98,99,Way Less Sad,AJR,-,99
99,100,Clear Da Air,Moneybagg Yo,-,100

# 7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/. You have to find the following details:
A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [49]:
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [50]:
Name=[]
Designation=[]
Company=[]
Skills_they_Hire=[]
Location=[]

In [51]:
def naukri(url):
    driver=webdriver.Chrome('chromedriver.exe')
    driver.get(url)
    
    recruiter=driver.find_element_by_xpath("//div[@class='subMenu']/ul/li[1]/a")
    url=recruiter.get_attribute('href')
    driver.get(url)
    
    search=driver.find_element_by_xpath("//div[@id='skill']/div[1]/div[2]/input")
    search.send_keys('Data Science')
    search_button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']").click()
    
    for page in range(0,116):
        
        name=driver.find_elements_by_xpath("//a[@class='ellipsis']/span")
        for n in name:
            Name.append(n.text)
        
        designation=driver.find_elements_by_xpath("//p[@class='highlightable']/span[1]")
        for d in designation:
            Designation.append(d.text)

        company=driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")
        for c in company:
            Company.append(c.text)

        skill=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
        for s in skill:
            Skills_they_Hire.append(s.text)
    
        location=driver.find_elements_by_xpath("//p[@class='highlightable']/span[2]/small")
        for l in location:
            Location.append(l.text)

        next_button=driver.find_elements_by_xpath("//div[@class='pagination']/button")
        for i in next_button:
            if i.text=='Next':
                i.click()
                
            
            
naukri('https://www.naukri.com/')

In [54]:
Recruiter=pd.DataFrame({'Name':Name[0:5761],'Designation':Designation[0:5761],'Company':Company[0:5761],'Skills':Skills_they_Hire[0:5761],'Location':Location[0:5761]})
Recruiter

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,Talent Acquisition Executive,Recruitment Professional,XenonStack,"Web Designing, html5, Angular.js, seo, hadoop,...",Chandigarh
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
...,...,...,...,...,...
5756,Shailesh Parmar,Company Recruiter,Voice Media Communication,Not Specified,Pune
5757,Jaganathan Rajapandi,Operations Head,J2aspen Info Services,"Pagination, Qc, Proof Reading, Xml, E-publishi...",Bharuch
5758,Santosh Hegde,Company HR,Appobile Labs,Not Specified,Mumbai
5759,Jagdish Teli,Head Training and Placement Officer,"Jawaharlal Institute of Technology,Khargone","For freshers and experienced, Letter Drafting,...",Thane
5760,Dhara,Talent Acquisition Pan India SAP,DELTA SYS-TECH(INDIA) PVT LTD,Not Specified,Kolkata

# 8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/. You have to find the following details:
A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [74]:
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [75]:
driver=webdriver.Chrome('chromedriver.exe')

In [76]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')

In [77]:
Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher=[]
Genre=[]

In [78]:
book_name=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
for bn in book_name:
    Book_name.append(bn.text)

In [79]:
author_name=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
for an in author_name:
    Author_name.append(an.text)

In [80]:
volume_sold=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
for vs in volume_sold:
    Volumes_sold.append(vs.text)

In [81]:
publisher=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
for p in publisher:
    table[@class='in-article sortable']/tbody/tr/td[2]ublisher.append(p.text)

In [82]:
genre=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
for g in genre:
    Genre.append(g.text)

In [85]:
Top_100_books=pd.DataFrame({'Book Name':Book_name,'Author':Author_name,'Volume':Volumes_sold,'Publisher':Publisher,'Genre':Genre})
Top_100_books

,Book Name,Author,Volume,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ . You have to find the following details:
A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [196]:
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [197]:
driver=webdriver.Chrome('chromedriver.exe')

In [198]:
driver.get('https://www.imdb.com/list/ls095964455/')

In [199]:
Name=[]
Year_span=[]
Genre=[]
Run_time=[]
Ratings=[]
Votes=[]

In [214]:
name=driver.find_elements_by_xpath("//div[@class='lister-item-content']/h3/a")
for n in name:
    Name.append(n.text)

In [215]:
year_span=driver.find_elements_by_xpath("//div[@class='lister-item-content']/h3/span[2]")
for ys in year_span:
    Year_span.append(ys.text)

In [216]:
genre=driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[1]/span[5]")
for g in genre:
    Genre.append(g.text)

In [217]:
run_time=driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[1]/span[3]")
for rt in run_time:
    Run_time.append(rt.text)

In [218]:
rating=driver.find_elements_by_xpath("//div[@class='lister-item-content']/div[1]/div[1]/span[2]")
for r in rating:
    Ratings.append(r.text)

In [219]:
votes=driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]")
for v in votes:
    Votes.append(v.text)

In [220]:
IMDB=pd.DataFrame({'Name':Name,'Year Span':Year_span,'Genre':Genre,'Run Time':Run_time,'Ratings':Ratings,'Votes':Votes})
IMDB

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,805,137"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"849,775"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"868,786"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"260,551"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"221,565"
...,...,...,...,...,...,...
195,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,266"
196,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"54,717"
197,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"165,795"
198,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.2,"34,631"
199,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"188,641"

# 10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/. You have to find the following details:
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

In [227]:
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [228]:
driver=webdriver.Chrome('chromedriver.exe')

In [229]:
driver.get('https://archive.ics.uci.edu/')

WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: chrome=90.0.4430.93)